inputs:
  num-octocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  octocat-eye-color:
    description: 'Eye color of the Octocats'
    required: true


outputs:
  sum: # id of the output
    description: 'The sum of the inputs'
