name: GitHub Actions Demo

on:
  push:
    branches: [ main ]

jobs:
  run-mlops:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: check dir
        run: |
          pwd
          ls -lh
          env


      
